package main;

import model.Vehicle;
import model.VehicleStatus;
import model.VehicleType;
import model.VehicleTypeName;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

public class TestDatabase implements Database {
    @Override
    public DatabaseResponse<List<Vehicle>> getVehicles(VehicleTypeName type, String location, LocalDateTime from, LocalDateTime to) {
        List<Vehicle> vehicles = new ArrayList<>();
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        vehicles.add(new Vehicle(ThreadLocalRandom.current().nextInt(2, 100000), "L" + ThreadLocalRandom.current().nextInt(2, 100000), "M" + ThreadLocalRandom.current().nextInt(2, 100000), "M_" + ThreadLocalRandom.current().nextInt(2, 20), ThreadLocalRandom.current().nextInt(1990, 2050) + "", "c--", ThreadLocalRandom.current().nextInt(2, 100000), VehicleStatus.FOR_RENT, null, VehicleTypeName.FULLSIZE));
        return new TestDatabaseResponse<>("test query", true, "success test response", vehicles);
    }
    
    @Override
    public DatabaseResponse<String> generateDailyRentalReport() {
        return null;
    }
    
    @Override
    public DatabaseResponse<String> generateDailyBranchRentalReport(String branch) {
        return null;
    }
    
    @Override
    public DatabaseResponse<String> generateDailyReturnReport() {
        return null;
    }
    
    @Override
    public DatabaseResponse<String> generateDailyBranchReturnReport(String branch) {
        return null;
    }
    
    @Override
    public DatabaseResponse<Boolean> locationExists(String location) {
        return new TestDatabaseResponse<Boolean>("query location", true, "found location", true);
    }
    
    @Override
    public DatabaseResponse<String> reserveVehicle(VehicleTypeName type, String location) {
        return null;
    }
    
    @Override
    public DatabaseResponse<?> sendQuery(String query) {
        return null;
    }
}
